
libapp-objs +=apps/gui/widget/dialog/gui_dialog.o
libapp-objs +=apps/gui/widget/menu/gui_menu.o
libapp-objs +=apps/gui/widget/menu/gui_menu_adjust.o
libapp-objs +=apps/gui/widget/menu/gui_menu_quick.o
libapp-objs +=apps/gui/widget/menu/gui_menu_time.o
libapp-objs +=apps/gui/widget/menu/gui_menu_adas_calib.o
