
libapp-objs +=peripheral_mod/vin/sensor/ov4689_a12/AmbaIQParamOv4689_A12.o
libapp-objs +=peripheral_mod/vin/sensor/ov4689_a12/AmbaIQParamOv4689Hdr_A12.o
libapp-objs +=peripheral_mod/vin/sensor/ov4689_a12/sensor_ov4689_a12.o
libapp-objs +=peripheral_mod/vin/sensor/ov4689_a12/AmbaCalibParams_ov4689.o
