
libapp-objs +=apps/flow/pb/pb_multi.o
libapp-objs +=apps/flow/pb/pb_multi_func.o
libapp-objs +=apps/flow/pb/pb_multi_op.o
libapp-objs +=apps/flow/pb/pb_photo.o
libapp-objs +=apps/flow/pb/pb_photo_func.o
libapp-objs +=apps/flow/pb/pb_photo_op.o
libapp-objs +=apps/flow/pb/pb_video.o
libapp-objs +=apps/flow/pb/pb_video_func.o
libapp-objs +=apps/flow/pb/pb_video_op.o
libapp-objs +=apps/flow/pb/hdmi_test.o
libapp-objs +=apps/flow/pb/hdmi_test_func.o
libapp-objs +=apps/flow/pb/hdmi_test_op.o
