ifdef CONFIG_LCD_T20P52 
libapp-objs +=peripheral_mod/vout/lcd/t20p52/lcd_t20p52.o
endif

ifdef CONFIG_LCD_WDF9648W
libapp-objs +=peripheral_mod/vout/lcd/wdf9648w/lcd_wdf9648w.o
endif

ifdef CONFIG_LCD_T30P61 
libapp-objs +=peripheral_mod/vout/lcd/t30p61/lcd_t30p61.o
endif

ifdef CONFIG_LCD_EG020THEG1
libapp-objs +=peripheral_mod/vout/lcd/eg020theg1/lcd_eg020theg1.o
endif