
include $(srctree)/app/connected/app/apps/flow/disp_param/Makefile
include $(srctree)/app/connected/app/apps/flow/misc/Makefile
include $(srctree)/app/connected/app/apps/flow/pb/Makefile
include $(srctree)/app/connected/app/apps/flow/rec/Makefile
include $(srctree)/app/connected/app/apps/flow/thumb/Makefile
include $(srctree)/app/connected/app/apps/flow/usb/Makefile
include $(srctree)/app/connected/app/apps/flow/widget/Makefile
