/*============================================================================
 Machine Generated Configuration File!!! 
 DO NOT EDIT THIS FILE, unless you are aware of its effect.
 
 
 This file is needed for target configuration.
 This file is generated by eBinder Configurator, each time the project 
 configuration is edited.
 ============================================================================*/

#ifndef	__EB_PF_CONFIG_EXT_H__
#define	__EB_PF_CONFIG_EXT_H__

#define PF_UNICODE_INTERFACE_SUPPORT (1)
#define PF_FREE_CLUSTER_SEARCH_SUPPORT (1)

#endif	/*	__EB_PF_CONFIG_EXT_H__	*/
