/*============================================================================
 Machine Generated Configuration File!!! 
 DO NOT EDIT THIS FILE, unless you are aware of its effect.
 
 
 This file is needed for target configuration.
 This file is generated by eBinder Configurator, each time the project 
 configuration is edited.
 ============================================================================*/

#ifndef	__EB_PDM_CONFIG_H__
#define	__EB_PDM_CONFIG_H__

#define PDM_MAX_DISK PF_MAX_DISK

#define PDM_MAX_PARTITION PF_MAX_VOLUME

#define PDM_DISK_LOCK_ENABLE 0

#define PDM_PARTITION_LOCK_ENABLE 0

#define PDM_CRITICAL_SECTION_ENABLE PF_EXCLUSIVE_DISK_ACCESS_ENABLE

#define PDM_PARAM_CHECK_ENABLE PF_PARAM_CHECK_ENABLE

#endif	/*	__EB_PDM_CONFIG_H__	*/
