
libapp-objs +=peripheral_mod/vin/sensor/ar0230_a12/AmbaIQParamAr0230_A12.o
libapp-objs +=peripheral_mod/vin/sensor/ar0230_a12/AmbaIQParamAr0230Hdr_A12.o
libapp-objs +=peripheral_mod/vin/sensor/ar0230_a12/sensor_ar0230_a12.o
libapp-objs +=peripheral_mod/vin/sensor/ar0230_a12/AmbaCalibParams_ar0230.o
