
libapp-objs +=apps/flow/rec/rec_connected_cam.o
libapp-objs +=apps/flow/rec/rec_connected_cam_func.o
libapp-objs +=apps/flow/rec/rec_connected_cam_op.o

ifeq ($(CONFIG_APP_CONNECTED_AMBA_LINK),y)
libapp-objs +=apps/flow/rec/rec_connected_cam_netctrl.o
endif
