
libapp-objs +=peripheral_mod/vin/sensor/mn34222_a12/AmbaIQParamMn34222_A12.o
libapp-objs +=peripheral_mod/vin/sensor/mn34222_a12/AmbaIQParamMn34222Hdr_A12.o
libapp-objs +=peripheral_mod/vin/sensor/mn34222_a12/sensor_mn34222_a12.o
libapp-objs +=peripheral_mod/vin/sensor/mn34222_a12/AmbaCalibParams_mn34222.o
