
libapp-objs +=apps/flow/widget/menu/menu.o
libapp-objs +=apps/flow/widget/menu/menu_adjust.o
libapp-objs +=apps/flow/widget/menu/menu_pback.o
libapp-objs +=apps/flow/widget/menu/menu_photo.o
libapp-objs +=apps/flow/widget/menu/menu_quick.o
libapp-objs +=apps/flow/widget/menu/menu_setup.o
libapp-objs +=apps/flow/widget/menu/menu_time.o
libapp-objs +=apps/flow/widget/menu/menu_video.o
libapp-objs +=apps/flow/widget/menu/menu_adas_calib.o
