/**
  * @file src/app/apps/flow/widget/menu/connectedcam/menu_video.h
  *
  * Header of Video-related Menu Items
  *
  * History:
  *    2013/11/22 - [Martin Lai] created file
  *
  * Copyright (C) 2013, Ambarella, Inc.
  *
  * All rights reserved. No Part of this file may be reproduced, stored
  * in a retrieval system, or transmitted, in any form, or by any means,
  * electronic, mechanical, photocopying, recording, or otherwise,
  * without the prior consent of Ambarella, Inc.
  */
#ifndef APP_WIDGET_MENU_VIDEO_H_
#define APP_WIDGET_MENU_VIDEO_H_

__BEGIN_C_PROTO__

/*************************************************************************
 * Video menu definitions
 ************************************************************************/
typedef enum _MENU_VIDEO_ITEM_ID_e_ {
    MENU_VIDEO_SENSOR_RES = 0,
    MENU_VIDEO_YUV_RES,
    MENU_VIDEO_QUALITY,
    MENU_VIDEO_SELFTIMER,
    MENU_VIDEO_PRE_RECORD,
    MENU_VIDEO_TIME_LAPSE,
    MENU_VIDEO_DUAL_STREAMS,
    MENU_VIDEO_STREAMS_TYPE,
    MENU_VIDEO_STREAMING,
    MENU_VIDEO_DIGITAL_ZOOM,
    MENU_VIDEO_STAMP,
    MENU_VIDEO_REC_MODE,
    MENU_VIDEO_ADAS,
    MENU_VIDEO_ADAS_CALIB,
    MENU_VIDEO_ITEM_NUM
} MENU_VIDEO_ITEM_ID_e;

/**
* video mres selection table is in sensor config
**/
typedef enum _MENU_VIDEO_SENSOR_RES_SEL_ID_e_ {
    MENU_VIDEO_SENSOR_RES_1 = 0,
    MENU_VIDEO_SENSOR_RES_2,
    MENU_VIDEO_SENSOR_RES_3,
    MENU_VIDEO_SENSOR_RES_4,
    MENU_VIDEO_SENSOR_RES_5,
    MENU_VIDEO_SENSOR_RES_6,
    MENU_VIDEO_SENSOR_RES_7,
    MENU_VIDEO_SENSOR_RES_8,
    MENU_VIDEO_SENSOR_RES_9,
    MENU_VIDEO_SENSOR_RES_10,
    MENU_VIDEO_SENSOR_RES_11,
    MENU_VIDEO_SENSOR_RES_12,
    MENU_VIDEO_SENSOR_RES_13,
    MENU_VIDEO_SENSOR_RES_14,
    MENU_VIDEO_SENSOR_RES_15,
    MENU_VIDEO_SENSOR_RES_16,
    MENU_VIDEO_SENSOR_RES_17,
    MENU_VIDEO_SENSOR_RES_18,
    MENU_VIDEO_SENSOR_RES_19,
    MENU_VIDEO_SENSOR_RES_20,
    MENU_VIDEO_SENSOR_RES_21,
    MENU_VIDEO_SENSOR_RES_22,
    MENU_VIDEO_SENSOR_RES_23,
    MENU_VIDEO_SENSOR_RES_24,
    MENU_VIDEO_SENSOR_RES_25,
    MENU_VIDEO_SENSOR_RES_26,
    MENU_VIDEO_SENSOR_RES_27,
    MENU_VIDEO_SENSOR_RES_28,
    MENU_VIDEO_SENSOR_RES_29,
    MENU_VIDEO_SENSOR_RES_30,
    MENU_VIDEO_SENSOR_RES_31,
    MENU_VIDEO_SENSOR_RES_32,
    MENU_VIDEO_SENSOR_RES_SEL_NUM
} MENU_VIDEO_SENSOR_RES_SEL_ID_e;

typedef enum _MENU_VIDEO_YUV_RES_SEL_ID_e_ {
    MENU_VIDEO_YUV_RES_1 = 0,
    MENU_VIDEO_YUV_RES_2,
    MENU_VIDEO_YUV_RES_3,
    MENU_VIDEO_YUV_RES_4,
    MENU_VIDEO_YUV_RES_5,
    MENU_VIDEO_YUV_RES_6,
    MENU_VIDEO_YUV_RES_7,
    MENU_VIDEO_YUV_RES_8,
    MENU_VIDEO_YUV_RES_9,
    MENU_VIDEO_YUV_RES_10,
    MENU_VIDEO_YUV_RES_11,
    MENU_VIDEO_YUV_RES_12,
    MENU_VIDEO_YUV_RES_13,
    MENU_VIDEO_YUV_RES_14,
    MENU_VIDEO_YUV_RES_15,
    MENU_VIDEO_YUV_RES_16,
    MENU_VIDEO_YUV_RES_17,
    MENU_VIDEO_YUV_RES_18,
    MENU_VIDEO_YUV_RES_19,
    MENU_VIDEO_YUV_RES_20,
    MENU_VIDEO_YUV_RES_21,
    MENU_VIDEO_YUV_RES_22,
    MENU_VIDEO_YUV_RES_23,
    MENU_VIDEO_YUV_RES_24,
    MENU_VIDEO_YUV_RES_25,
    MENU_VIDEO_YUV_RES_26,
    MENU_VIDEO_YUV_RES_27,
    MENU_VIDEO_YUV_RES_28,
    MENU_VIDEO_YUV_RES_29,
    MENU_VIDEO_YUV_RES_30,
    MENU_VIDEO_YUV_RES_31,
    MENU_VIDEO_YUV_RES_32,
    MENU_VIDEO_YUV_RES_SEL_NUM
} MENU_VIDEO_YUV_RES_SEL_ID_e;

typedef enum _MENU_VIDEO_QUALITY_SEL_ID_e_ {
    MENU_VIDEO_QUALITY_SFINE = 0,
    MENU_VIDEO_QUALITY_FINE,
    MENU_VIDEO_QUALITY_NORMAL,
    MENU_VIDEO_QUALITY_SEL_NUM
} MENU_VIDEO_QUALITY_SEL_ID_e;

typedef enum _MENU_VIDEO_SELFTIMER_SEL_ID_e_ {
    MENU_VIDEO_SELFTIMER_OFF = 0,
    MENU_VIDEO_SELFTIMER_3S,
    MENU_VIDEO_SELFTIMER_5S,
    MENU_VIDEO_SELFTIMER_10S,
    MENU_VIDEO_SELFTIMER_SEL_NUM
} MENU_VIDEO_SELFTIMER_SEL_ID_e;

typedef enum _MENU_VIDEO_PRE_RECORD_SEL_ID_e_ {
    MENU_VIDEO_PRE_RECORD_OFF = 0,
    MENU_VIDEO_PRE_RECORD_ON,
    MENU_VIDEO_PRE_RECORD_SEL_NUM
} MENU_VIDEO_PRE_RECORD_SEL_ID_e;

typedef enum _MENU_VIDEO_TIME_LAPSE_SEL_ID_e_ {
    MENU_VIDEO_TIME_LAPSE_OFF = 0,
    MENU_VIDEO_TIME_LAPSE_2S,
    MENU_VIDEO_TIME_LAPSE_SEL_NUM
} MENU_VIDEO_TIME_LAPSE_SEL_ID_e;

typedef enum _MENU_VIDEO_DUAL_STREAMS_SEL_ID_e_ {
    MENU_VIDEO_DUAL_STREAMS_OFF = 0,
    MENU_VIDEO_DUAL_STREAMS_ON,
    MENU_VIDEO_DUAL_STREAMS_SEL_NUM
} MENU_VIDEO_DUAL_STREAMS_SEL_ID_e;

typedef enum _MENU_VIDEO_STREAMS_TYPE_SEL_ID_e_ {
#if defined(CONFIG_AMBA_STREAMING) || defined(CONFIG_APP_CONNECTED_AMBA_LINK)
    MENU_VIDEO_STREAMS_TYPE_OFF = 0,
#if defined(CONFIG_SUPPORT_BOSS) || defined(CONFIG_APP_CONNECTED_AMBA_LINK)
    MENU_VIDEO_STREAMS_TYPE_RTSP,
#endif
    MENU_VIDEO_STREAMS_TYPE_MJPG,
    MENU_VIDEO_STREAMS_TYPE_UVC_MJPG,
    MENU_VIDEO_STREAMS_TYPE_HLS,
    MENU_VIDEO_STREAMS_TYPE_SEL_NUM
#else
    MENU_VIDEO_STREAMS_TYPE_OFF = 0,
    MENU_VIDEO_STREAMS_TYPE_MJPG,
    MENU_VIDEO_STREAMS_TYPE_SEL_NUM
#endif
} MENU_VIDEO_STREAMS_TYPE_SEL_ID_e;

typedef enum _MENU_VIDEO_STREAMING_SEL_ID_e_ {
    MENU_VIDEO_STREAMING_OFF = 0,
    MENU_VIDEO_STREAMING_ON,
    MENU_VIDEO_STREAMING_SEL_NUM
} MENU_VIDEO_STREAMING_SEL_ID_e;


typedef enum _MENU_VIDEO_DIGIAL_ZOOM_SEL_ID_e_ {
    MENU_VIDEO_DIGITAL_ZOOM_OFF = 0,
    MENU_VIDEO_DIGITAL_ZOOM_ON,
    MENU_VIDEO_DIGITAL_ZOOM_NUMX,
    MENU_VIDEO_DIGITAL_ZOOM_SEL_NUM
} MENU_VIDEO_DIGIAL_ZOOM_SEL_ID_e;

typedef enum _MENU_VIDEO_STAMP_SEL_ID_e_ {
    MENU_VIDEO_STAMP_OFF = 0,
    MENU_VIDEO_STAMP_DATE,
    MENU_VIDEO_STAMP_TIME,
    MENU_VIDEO_STAMP_BOTH,
    MENU_VIDEO_STAMP_SEL_NUM
} MENU_VIDEO_STAMP_SEL_ID_e;

typedef enum _MENU_VIDEO_REC_MODE_SEL_ID_e_ {
    MENU_VIDEO_REC_MODE_VIDEO_MODE = 0,
    MENU_VIDEO_REC_MODE_STILL_MODE,
    MENU_VIDEO_REC_MODE_SEL_NUM
} MENU_VIDEO_REC_MODE_SEL_ID_e;

typedef enum _MENU_VIDEO_ADAS_SEL_ID_e_ {
    MENU_VIDEO_ADAS_OFF = 0,
    MENU_VIDEO_ADAS_ON,
    MENU_VIDEO_ADAS_SEL_NUM
} MENU_VIDEO_ADAS_SEL_ID_e;

typedef enum _MENU_VIDEO_ADAS_CALIBRATION_SEL_ID_e_ {
    MENU_VIDEO_ADAS_CALIBRATION_SET = 0,
    MENU_VIDEO_ADAS_CALIBRATION_SEL_NUM
} MENU_VIDEO_ADAS_CALIBRATION_SEL_ID_e;

__END_C_PROTO__

#endif /* APP_WIDGET_MENU_VIDEO_H_ */
