/**
  * @file src/app/apps/flow/widget/menu/connectedcam/menu_setup.h
  *
  * Header of Setup-related Menu Items
  *
  * History:
  *    2013/11/22 - [Martin Lai] created file
  *
  * Copyright (C) 2013, Ambarella, Inc.
  *
  * All rights reserved. No Part of this file may be reproduced, stored
  * in a retrieval system, or transmitted, in any form, or by any means,
  * electronic, mechanical, photocopying, recording, or otherwise,
  * without the prior consent of Ambarella, Inc.
  */
#ifndef APP_WIDGET_MENU_SETUP_H_
#define APP_WIDGET_MENU_SETUP_H_


__BEGIN_C_PROTO__

/*************************************************************************
 * setup menu definitions
 ************************************************************************/
typedef enum _MENU_SETUP_ITEM_ID_e_ {
    MENU_SETUP_SYSTEM_TYPE,
    MENU_SETUP_DMF_MODE,
    MENU_SETUP_TIME,
    MENU_SETUP_DATE_TIME_DISPLAY,
    MENU_SETUP_FORMAT,
    MENU_SETUP_DEFAULT,
    MENU_SETUP_LCD_CONTROL,
    MENU_SETUP_POWEROFF,
    MENU_SETUP_POWERSAVING,
    MENU_SETUP_HDMI,
    MENU_SETUP_FLASHLIGHT,
    MENU_SETUP_USB_MODE,
    MENU_SETUP_INPUT_DIMENSION_MODE,
    MENU_SETUP_OUTPUT_DIMENSION_MODE,
    MENU_SETUP_WIFI,
    MENU_SETUP_WIFI_CONFIG,
    MENU_SETUP_VERSION,
    MENU_SETUP_ITEM_NUM
} MENU_SETUP_ITEM_ID_e;

typedef enum _MENU_SETUP_SYSTEM_TYPE_SEL_ID_e_ {
    MENU_SETUP_SYSTEM_TYPE_NTSC = 0,
    MENU_SETUP_SYSTEM_TYPE_PAL,
    MENU_SETUP_SYSTEM_TYPE_SEL_NUM
} MENU_SETUP_SYSTEM_TYPE_SEL_ID_e;

typedef enum _MENU_SETUP_DMF_MODE_SEL_ID_e_ {
    MENU_SETUP_DMF_MODE_RESET = 0,
    MENU_SETUP_DMF_MODE_SERIAL,
    MENU_SETUP_DMF_MODE_SEL_NUM
} MENU_SETUP_DMF_MODE_SEL_ID_e;

typedef enum _MENU_SETUP_TIME_SEL_ID_e_ {
    MENU_SETUP_TIME_YEAR = 0,
    MENU_SETUP_TIME_MONTH,
    MENU_SETUP_TIME_DAY,
    MENU_SETUP_TIME_HOUR,
    MENU_SETUP_TIME_MINUTE,
    MENU_SETUP_TIME_SEL_NUM
} MENU_SETUP_TIME_SEL_ID_e;

typedef enum _MENU_SETUP_DATE_TIME_DISPLAY_SEL_ID_e_ {
    MENU_SETUP_DATE_TIME_DISPLAY_OFF = 0,
    MENU_SETUP_DATE_TIME_DISPLAY_DATE,
    MENU_SETUP_DATE_TIME_DISPLAY_TIME,
    MENU_SETUP_DATE_TIME_DISPLAY_BOTH,
    MENU_SETUP_DATE_TIME_DISPLAY_SEL_NUM
} MENU_SETUP_DATE_TIME_DISPLAY_SEL_ID_e;

typedef enum _MENU_SETUP_LCD_CTRL_SEL_ID_e_ {
    MENU_SETUP_LCD_CONTROL_BRIGHTNESS = 0,
    MENU_SETUP_LCD_CONTROL_CONTRAST,
    MENU_SETUP_LCD_CONTROL_COLOR_BALANCE,
    MENU_SETUP_LCD_CONTROL_SEL_NUM
} MENU_SETUP_LCD_CTRL_SEL_ID_e;

typedef enum _MENU_SETUP_POWEROFF_SEL_ID_e_ {
    MENU_SETUP_POWEROFF_OFF = 0,
    MENU_SETUP_POWEROFF_3M,
    MENU_SETUP_POWEROFF_5M,
    MENU_SETUP_POWEROFF_SEL_NUM
} MENU_SETUP_POWEROFF_SEL_ID_e;

typedef enum _MENU_SETUP_POWERSAVING_SEL_ID_e_ {
    MENU_SETUP_POWERSAVING_OFF = 0,
    MENU_SETUP_POWERSAVING_ON,
    MENU_SETUP_POWERSAVING_SEL_NUM
} MENU_SETUP_POWERSAVING_SEL_ID_e;

typedef enum _MENU_SETUP_HDMI_FUNC_SEL_ID_e_ {
    MENU_SETUP_HDMI_OFF = 0,
    MENU_SETUP_HDMI_ON,
    MENU_SETUP_HDMI_SEL_NUM
} MENU_SETUP_HDMI_FUNC_SEL_ID_e;

typedef enum _MENU_SETUP_FLASHLIGHT_SEL_ID_e_ {
    MENU_SETUP_FLASHLIGHT_OFF = 0,
    MENU_SETUP_FLASHLIGHT_ON,
    MENU_SETUP_FLASHLIGHT_AUTO,
    MENU_SETUP_FLASHLIGHT_SEL_NUM
} MENU_SETUP_FLASHLIGHT_SEL_ID_e;

typedef enum _MENU_SETUP_USB_MODE_SEL_ID_e_ {
    MENU_SETUP_USB_MODE_MSC = 0,
    MENU_SETUP_USB_MODE_AMAGE,
#ifdef CONFIG_ASD_USB_RS232_ENABLE
    MENU_SETUP_USB_MODE_RS232,
#endif
    MENU_SETUP_USB_MODE_SEL_NUM
} MENU_SETUP_USB_MODE_SEL_ID_e;

typedef enum _MENU_SETUP_INPUT_DIMENSION_MODE_SEL_ID_e_ {
    MENU_SETUP_INPUT_2D_R = 0,
    MENU_SETUP_INPUT_2D_L,
    MENU_SETUP_INPUT_3D,
    MENU_SETUP_INPUT_DIMENSION_MODE_SEL_NUM
} MENU_SETUP_INPUT_DIMENSION_MODE_SEL_ID_e;

typedef enum _MENU_SETUP_OUTPUT_DIMENSION_MODE_SEL_ID_e_ {
    MENU_SETUP_OUTPUT_2D = 0,
    MENU_SETUP_OUTPUT_2D_RIGHT,
    MENU_SETUP_OUTPUT_2D_LEFT,
    MENU_SETUP_OUTPUT_3D,
    MENU_SETUP_OUTPUT_DIMENSION_MODE_SEL_NUM
} MENU_SETUP_OUTPUT_DIMENSION_MODE_SEL_ID_e;

typedef enum _MENU_SETUP_WIFI_SEL_ID_e_ {
    MENU_SETUP_WIFI_OFF = 0,
    MENU_SETUP_WIFI_ON,
    MENU_SETUP_WIFI_ON_AP,
    MENU_SETUP_WIFI_SEL_NUM
} MENU_SETUP_WIFI_SEL_ID_e;

typedef enum _MENU_SETUP_WIFI_CONFIG_SEL_ID_e_ {
    MENU_SETUP_WIFI_CONFIG_0 = 0,
    MENU_SETUP_WIFI_CONFIG_1,
    MENU_SETUP_WIFI_CONFIG_2,
    MENU_SETUP_WIFI_CONFIG_3,
    MENU_SETUP_WIFI_CONFIG_4,
    MENU_SETUP_WIFI_CONFIG_SEL_NUM
} MENU_SETUP_WIFI_CONFIG_SEL_ID_e;
__END_C_PROTO__

#endif /* APP_WIDGET_MENU_SETUP_H_ */
