
libapp-objs +=system/app_pref.o
libapp-objs +=system/app_util.o
libapp-objs +=system/handler.o
libapp-objs +=system/t_app.o

ifeq ($(CONFIG_APP_CONNECTED_AMBA_LINK),y)
libapp-objs +=system/onlinePlayback.o
endif