
libapp-objs +=peripheral_mod/vin/sensor/imx117_a12/AmbaIQParamImx117_A12.o
libapp-objs +=peripheral_mod/vin/sensor/imx117_a12/sensor_imx117_a12.o
libapp-objs +=peripheral_mod/vin/sensor/imx117_a12/AmbaCalibParams_imx117.o
