
libapp-objs +=peripheral_mod/vin/sensor/imx206_a12/AmbaIQParamImx206_A12.o
libapp-objs +=peripheral_mod/vin/sensor/imx206_a12/sensor_imx206_a12.o
libapp-objs +=peripheral_mod/vin/sensor/imx206_a12/AmbaCalibParams_imx206.o
