
libapp-objs +=peripheral_mod/vin/sensor/mn34120_a12/AmbaIQParamMn34120_A12.o
libapp-objs +=peripheral_mod/vin/sensor/mn34120_a12/sensor_mn34120_a12.o
libapp-objs +=peripheral_mod/vin/sensor/mn34120_a12/AmbaCalibParams_mn34120.o
