
libapp-objs +=peripheral_mod/vin/sensor/imx290_a12/AmbaIQParamImx290_A12.o
libapp-objs +=peripheral_mod/vin/sensor/imx290_a12/AmbaIQParamImx290Hdr_A12.o
libapp-objs +=peripheral_mod/vin/sensor/imx290_a12/sensor_imx290_a12.o
libapp-objs +=peripheral_mod/vin/sensor/imx290_a12/AmbaCalibParams_imx290.o
