/**
  * @file src/app/apps/gui/resource/connectedcam/gui_table.h
  *
  * Header for GUI object table
  *
  * History:
  *    2013/11/22 - [Martin Lai] created file
  *
  * Copyright (C) 2013, Ambarella, Inc.
  *
  * All rights reserved. No Part of this file may be reproduced, stored
  * in a retrieval system, or transmitted, in any form, or by any means,
  * electronic, mechanical, photocopying, recording, or otherwise,
  * without the prior consent of Ambarella, Inc.
  */
#ifndef APP_GUI_TABLE_H_
#define APP_GUI_TABLE_H_

#include "gui_resource.h"

__BEGIN_C_PROTO__

typedef enum _GUI_LAYER_ID_e_ {
    GP_MAIN_0,
    GP_MAIN_1,
    GP_MAIN_2,
    GP_MAIN_3,
    GP_MENU_0,
    GP_MENU_1,
    GP_MENU_2,
    GP_SUBMENU_0,
    GP_SUBMENU_1,
    GP_SUBMENU_2
} GUI_LAYER_ID_e;


typedef enum _GUI_OBJ_ID_e_ {
    /** General */
    GOBJ_APP_ICON = 0,
    GOBJ_BATTERY,
    GOBJ_DC_PLUG,
    GOBJ_CARD_CURSOR,
    GOBJ_CARD,
    GOBJ_CARD_STATE,
    GOBJ_DISPLAY_ICON,
    GOBJ_MENU_ICON,
    GOBJ_RETURN_ICON,    //010
    GOBJ_MIC_ICON,
    GOBJ_WARNING,
    GOBJ_FWUPDATE_RATIO,
    GOBJ_FWUPDATE_STAGE,
    GOBJ_USB_MSG,
    GOBJ_PRINT_MSG,
    GOBJ_PRINT_MSG_2,

    /** Fullview status icons */
    GOBJ_FV_ICON_UP_1_CURSOR,
    GOBJ_FV_ICON_UP_1,
    GOBJ_FV_ICON_UP_2_CURSOR,//020
    GOBJ_FV_ICON_UP_2,
    GOBJ_FV_ICON_UP_3_CURSOR,
    GOBJ_FV_ICON_UP_3,
    GOBJ_FV_ICON_UP_4_CURSOR,
    GOBJ_FV_ICON_UP_4,
    GOBJ_FV_ICON_LEFT_1_CURSOR,
    GOBJ_FV_ICON_LEFT_1,
    GOBJ_FV_ICON_LEFT_2_CURSOR,
    GOBJ_FV_ICON_LEFT_2,
    GOBJ_FV_ICON_LEFT_3_CURSOR,//030
    GOBJ_FV_ICON_LEFT_3,
    GOBJ_FV_ICON_LEFT_4_CURSOR,
    GOBJ_FV_ICON_LEFT_4,
    GOBJ_FV_ICON_LEFT_5_CURSOR,
    GOBJ_FV_ICON_LEFT_5,

    /** Recorder mode */
    GOBJ_REC_STATE,
    GOBJ_REC_TIME,
    GOBJ_REC_EMERGENCY,

    /** Thumbnail mode */
    GOBJ_THUMB_3_TAB_BASE,
    GOBJ_THUMB_3_TAB_HL_1,
    GOBJ_THUMB_3_TAB_HL_2,//040
    GOBJ_THUMB_3_TAB_HL_3,
    GOBJ_THUMB_SEP_UP,
    GOBJ_THUMB_SEP_LEFT,
    GOBJ_THUMB_GLOW_LEFT,//050
    GOBJ_THUMB_GLOW_RIGHT,
    GOBJ_THUMB_DEL,
    GOBJ_THUMB_PROTECT,
    GOBJ_THUMB_FILENAME,
#if 0
    GOBJ_THUMB_PICKUP_SELECT_1,
    GOBJ_THUMB_PICKUP_SELECT_2,
    GOBJ_THUMB_PICKUP_SELECT_3,
    GOBJ_THUMB_PICKUP_SELECT_4,
    GOBJ_THUMB_PICKUP_SELECT_5,
    GOBJ_THUMB_PICKUP_SELECT_6,//060

    GOBJ_THUMB2_PICKUP_SELECT_1,
    GOBJ_THUMB2_PICKUP_SELECT_2,//070
    GOBJ_THUMB2_PICKUP_SELECT_3,
    GOBJ_THUMB2_PICKUP_SELECT_4,
    GOBJ_THUMB2_PICKUP_SELECT_5,
    GOBJ_THUMB2_PICKUP_SELECT_6,
    GOBJ_THUMB2_PICKUP_SELECT_7,
    GOBJ_THUMB2_PICKUP_SELECT_8,
    GOBJ_THUMB2_PICKUP_SELECT_9,
    GOBJ_THUMB2_PICKUP_SELECT_10,
    GOBJ_THUMB2_PICKUP_SELECT_11,
    GOBJ_THUMB2_PICKUP_SELECT_12,//080
    GOBJ_THUMB2_PICKUP_SELECT_13,
    GOBJ_THUMB2_PICKUP_SELECT_14,
    GOBJ_THUMB2_PICKUP_SELECT_15,

    GOBJ_THUMB3_FILENAME,
    GOBJ_THUMB3_LEFTARROW,
    GOBJ_THUMB3_RIGHTARROW,
    GOBJ_THUMB3_FILECOUNT,
#endif
    /** Fullview pb mode */
    GOBJ_PB_MEDIA_RES,
    GOBJ_PB_MEDIA_AR,
    GOBJ_PB_CONTROL_BAR,//090
    GOBJ_PB_STATUS_BAR_BASE,
    GOBJ_PB_STATUS_BAR,
    GOBJ_PB_STATUS_BAR_HL,
    GOBJ_PB_STATUS_BAR_IDX,
    GOBJ_PB_PLAY_TIME,
    GOBJ_PB_TOTAL_TIME,
    GOBJ_PB_PLAY_TOTAL_TIME_SEP,
    GOBJ_PB_PLAY_STATE,
    GOBJ_PB_FILENAME,
    GOBJ_PB_ZOOM_TAG,//100
    GOBJ_PB_ZOOM_RATIO,
    GOBJ_PB_SPEED_RATIO,
    GOBJ_PB_TV_FILENAME,

    /** Zoom bar */
    GOBJ_ZOOMBAR_BASE,
    GOBJ_ZOOMBAR_WIDE,    /** zoomout */
    GOBJ_ZOOMBAR_TELE,    /** zoomin */
    GOBJ_ZOOMBAR_HL,
    GOBJ_ZOOMBAR_INDEX,
    GOBJ_ZOOMBAR_TAG,    /** ozoom/dzoom */    //130
#if 0
    /** face rectangles */
    GOBJ_FACE_RECT_1,
    GOBJ_FACE_RECT_2,
    GOBJ_FACE_RECT_3,
    GOBJ_FACE_RECT_4,
    GOBJ_FACE_RECT_5,
    GOBJ_FACE_RECT_6,
    GOBJ_FACE_RECT_7,
    GOBJ_FACE_RECT_8,
    GOBJ_FACE_RECT_9,
    GOBJ_FACE_RECT_10,//140
    GOBJ_FACE_RECT_11,
    GOBJ_FACE_RECT_12,
    GOBJ_FACE_RECT_13,
    GOBJ_FACE_RECT_14,
    GOBJ_FACE_RECT_15,
    GOBJ_FACE_RECT_16,
    GOBJ_FACE_RECT_17,
    GOBJ_FACE_RECT_18,
    GOBJ_FACE_RECT_19,
    GOBJ_FACE_RECT_20,//150
#endif
    /** Main menu */
    GOBJ_MENU_TAB_1,
    GOBJ_MENU_TAB_2,
    GOBJ_MENU_TAB_3,
    GOBJ_MENU_TAB_4,
    GOBJ_MENU_RECT_1,
    GOBJ_MENU_RECT_2,
    GOBJ_MENU_RECT_3,
    GOBJ_MENU_RECT_4,
    GOBJ_MENU_STRING_1,
    GOBJ_MENU_STRING_2,//160
    GOBJ_MENU_STRING_3,
    GOBJ_MENU_STRING_4,

    /** Quick menu */
    GOBJ_QMENU_BG,
    GOBJ_QMENU_OPT_HL,
    GOBJ_QMENU_OPT_1,
    GOBJ_QMENU_OPT_2,
    GOBJ_QMENU_OPT_3,
    GOBJ_QMENU_OPT_4,
    GOBJ_QMENU_OPT_5,
    GOBJ_QMENU_SET,//170
    GOBJ_QMENU_CANCEL,
    GOBJ_QMENU_UP,
    GOBJ_QMENU_DOWN,
    GOBJ_QMENU_DESC,
    GOBJ_QMENU_PAGE,

    /** Adjusting menu */
    GOBJ_AMENU_BAR_BASE,
    GOBJ_AMENU_BAR_HL,
    GOBJ_AMENU_BAR_IDX,
    GOBJ_AMENU_ICON_LEFT,
    GOBJ_AMENU_ICON_RIGHT,//180
    GOBJ_AMENU_SET,
    GOBJ_AMENU_CANCEL,
    GOBJ_AMENU_TITLE,
    GOBJ_AMENU_VALUE,

    /** Time setup menu */
    GOBJ_TMENU_BASE,
    GOBJ_TMENU_TITLE,
    GOBJ_TMENU_VAL_HL,
    GOBJ_TMENU_YEAR,
    GOBJ_TMENU_MONTH,
    GOBJ_TMENU_DAY,//190
    GOBJ_TMENU_HOUR,
    GOBJ_TMENU_MINUTE,
    GOBJ_TMENU_Y_M_SEP,
    GOBJ_TMENU_M_D_SEP,
    GOBJ_TMENU_H_M_SEP,
#if 0
    /** Calibration module OSD */
    GOBJ_CALIB_BG,
    GOBJ_CALIB_PROCESS,

    /** Focus lock state */
    GOBJ_FOCUS_LOCK,//200

    /** Focus lock areas rectangles */
    GOBJ_FOCUS_LOCK_RECT_1,
    GOBJ_FOCUS_LOCK_RECT_2,
    GOBJ_FOCUS_LOCK_RECT_3,
    GOBJ_FOCUS_LOCK_RECT_4,
    GOBJ_FOCUS_LOCK_RECT_5,
    GOBJ_FOCUS_LOCK_RECT_6,
    GOBJ_FOCUS_LOCK_RECT_7,
    GOBJ_FOCUS_LOCK_RECT_8,
    GOBJ_FOCUS_LOCK_RECT_9,
    GOBJ_FOCUS_LOCK_RECT_10,//210
    GOBJ_FOCUS_LOCK_RECT_11,
    GOBJ_FOCUS_LOCK_RECT_12,
    GOBJ_FOCUS_LOCK_RECT_13,
    GOBJ_FOCUS_LOCK_RECT_14,
    GOBJ_FOCUS_LOCK_RECT_15,
    GOBJ_FOCUS_LOCK_RECT_16,
    GOBJ_FOCUS_LOCK_RECT_17,
    GOBJ_FOCUS_LOCK_RECT_18,
    GOBJ_FOCUS_LOCK_RECT_19,
    GOBJ_FOCUS_LOCK_RECT_20,//220
    GOBJ_FOCUS_LOCK_RECT_21,
    GOBJ_FOCUS_LOCK_RECT_22,
    GOBJ_FOCUS_LOCK_RECT_23,
    GOBJ_FOCUS_LOCK_RECT_24,
    GOBJ_FOCUS_LOCK_RECT_25,
    GOBJ_FOCUS_LOCK_RECT_26,
    GOBJ_FOCUS_LOCK_RECT_27,
    GOBJ_FOCUS_LOCK_RECT_28,
    GOBJ_FOCUS_LOCK_RECT_29,
    GOBJ_FOCUS_LOCK_RECT_30,//230
    GOBJ_FOCUS_LOCK_RECT_31,
    GOBJ_FOCUS_LOCK_RECT_32,
    GOBJ_FOCUS_LOCK_RECT_33,
    GOBJ_FOCUS_LOCK_RECT_34,
    GOBJ_FOCUS_LOCK_RECT_35,
    GOBJ_FOCUS_LOCK_RECT_36,
    GOBJ_FOCUS_LOCK_RECT_37,
    GOBJ_FOCUS_LOCK_RECT_38,
    GOBJ_FOCUS_LOCK_RECT_39,
    GOBJ_FOCUS_LOCK_RECT_40,//240
#endif

    GOBJ_SURROUND_RECT_0,
    GOBJ_SURROUND_RECT_1,
    GOBJ_SURROUND_RECT_2,
    GOBJ_SURROUND_RECT_3,
    GOBJ_SURROUND_RECT_4,
    GOBJ_SURROUND_RECT_5,

    /** ADAS calibration menu */
    GOBJ_ADAS_CALIB_SKY,
    GOBJ_ADAS_CALIB_HOOD,

    GOBJ_SURROUND_APP_ICON,
    GOBJ_SURROUND_CARD_STATE,
    GOBJ_SURROUND_FV_ICON_UP_1,
    GOBJ_SURROUND_FV_ICON_UP_2,
    GOBJ_SURROUND_FV_ICON_UP_3,
    GOBJ_SURROUND_FV_ICON_UP_4,

#ifdef CONFIG_ASD_ADAS_GRAPHICS
    // gps status
    GOBJ_GPS_STATUS,
    GOBJ_FACE_RECT_1,
    GOBJ_FACE_RECT_2,
    GOBJ_FACE_RECT_3,
    GOBJ_FACE_RECT_4,
    GOBJ_FACE_RECT_5,
    GOBJ_FACE_RECT_INFO,
#endif
    GOBJ_END,    // Used for G2 ending sign

    GOBJ_NUM
}GUI_OBJ_ID_e;

#if (GUI_TABLE_SOURCE == GUI_TABLE_STATIC)
extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_960x480_8bit[];
//extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_960x480_16bit[];
extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_960x480_32bit[];
//extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_480x960_8bit[];
//extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_480x960_16bit[];
//extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_480x960_32bit[];
//extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_1920x135_tv_8bit[];
//extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_1920x135_tv_16bit[];
//extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_1920x135_tv_32bit[];
extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_960x540_tv_8bit[];
//extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_960x540_tv_16bit[];
extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_960x540_tv_32bit[];

extern APPLIB_GRAPHIC_UIOBJ_s gui_battery_960x480_32bit;
extern APPLIB_GRAPHIC_UIOBJ_s gui_app_icon_960x480_32bit;
#endif

typedef enum _GUI_BLEND_OBJ_ID_e_ {

    BOBJ_DATE_STREAM_0,
    BOBJ_DATE_STREAM_1,
    BOBJ_DATE_STREAM_2,
    BOBJ_DATE_STREAM_3,
    BOBJ_DATE_STREAM_4,
    BOBJ_DATE_STREAM_5,
    BOBJ_TIME_H_M_STREAM_0,
    BOBJ_TIME_H_M_STREAM_1,
    BOBJ_TIME_H_M_STREAM_2,
    BOBJ_TIME_H_M_STREAM_3,
    BOBJ_TIME_H_M_STREAM_4,
    BOBJ_TIME_H_M_STREAM_5,
    BOBJ_TIME_S_STREAM_0,
    BOBJ_TIME_S_STREAM_1,
    BOBJ_TIME_S_STREAM_2,
    BOBJ_TIME_S_STREAM_3,
    BOBJ_TIME_S_STREAM_4,
    BOBJ_TIME_S_STREAM_5,

    BOBJ_END,    // Used for G2 ending sign
    BOBJ_NUM
}GUI_BLEND_OBJ_ID_e;

#if (GUI_TABLE_SOURCE == GUI_TABLE_STATIC)
extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_blend_8bit[];
//extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_blend_16bit[];
extern APPLIB_GRAPHIC_UIOBJ_s *gui_table_blend_32bit[];
#endif

__END_C_PROTO__

#endif /* APP_GUI_TABLE_H_ */
