
libapp-objs +=apps/gui/resource/clut.o
libapp-objs +=apps/gui/resource/gui_settle.o
libapp-objs +=apps/gui/resource/gui_table_960x480_8bit.o
libapp-objs +=apps/gui/resource/gui_table_960x480_32bit.o
libapp-objs +=apps/gui/resource/gui_table_960x540_tv_8bit.o
libapp-objs +=apps/gui/resource/gui_table_960x540_tv_32bit.o
libapp-objs +=apps/gui/resource/gui_table_blend_8bit.o
libapp-objs +=apps/gui/resource/gui_table_blend_32bit.o
