ifdef CONFIG_SENSOR_SONY_IMX117
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/imx117_a12/Makefile
endif

ifdef CONFIG_SENSOR_SONY_IMX179
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/imx179_a12/Makefile
endif

ifdef CONFIG_SENSOR_SONY_IMX206
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/imx206_a12/Makefile
endif

ifdef CONFIG_SENSOR_SONY_IMX290
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/imx290_a12/Makefile
endif

ifdef CONFIG_SENSOR_OV4689
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/ov4689_a12/Makefile
endif

ifdef CONFIG_SENSOR_AR0330_PARALLEL
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/ar0330_parallel_a12/Makefile
endif

ifdef CONFIG_SENSOR_AR0230
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/ar0230_a12/Makefile
endif

ifdef CONFIG_SENSOR_MN34120
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/mn34120_a12/Makefile
endif

ifdef CONFIG_SENSOR_MN34222
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/mn34222_a12/Makefile
endif

ifdef CONFIG_SENSOR_MN34229
include $(srctree)/app/connected/app/peripheral_mod/vin/sensor/mn34229_a12/Makefile
endif