



.text

.globl begin_bst_image
.globl end_bst_image
.globl begin_bld_image
.globl end_bld_image
.globl begin_pba_image
.globl end_pba_image
.globl begin_sys_image
.globl end_sys_image
.globl begin_dsp_image
.globl end_dsp_image
.globl begin_rom_image
.globl end_rom_image
.globl begin_lnx_image
.globl end_lnx_image
.globl begin_dtb_image
.globl end_dtb_image
.globl begin_rfs_image
.globl end_rfs_image



begin_bst_image: .word __BEGIN_BST_IMAGE__







begin_bld_image: .word 0x0





begin_pba_image: .word 0x0





begin_sys_image: .word 0x0





begin_rom_image: .word 0x0





begin_dsp_image: .word 0x0





begin_lnx_image: .word 0x0





begin_dtb_image: .word 0x0





begin_rfs_image: .word 0x0





end_bst_image: .word __END_BST_IMAGE__







end_bld_image: .word 0x0





end_pba_image: .word 0x0





end_sys_image: .word 0x0





end_rom_image: .word 0x0





end_dsp_image: .word 0x0





end_lnx_image: .word 0x0





end_dtb_image: .word 0x0





end_rfs_image: .word 0x0
