
libapp-objs +=peripheral_mod/vin/sensor/mn34229_a12/AmbaIQParamMn34229_A12.o
libapp-objs +=peripheral_mod/vin/sensor/mn34229_a12/sensor_mn34229_a12.o
libapp-objs +=peripheral_mod/vin/sensor/mn34229_a12/AmbaCalibParams_mn34229.o
