
include $(srctree)/app/connected/app/peripheral_mod/ui/Makefile
include $(srctree)/app/connected/app/peripheral_mod/vin/Makefile
include $(srctree)/app/connected/app/peripheral_mod/vout/Makefile
include $(srctree)/app/connected/app/peripheral_mod/gps/Makefile

