
libapp-objs +=peripheral_mod/vin/sensor/ar0330_parallel_a12/AmbaIQParamAr0330_Parallel_A12.o
libapp-objs +=peripheral_mod/vin/sensor/ar0330_parallel_a12/sensor_ar0330_parallel_a12.o
libapp-objs +=peripheral_mod/vin/sensor/ar0330_parallel_a12/AmbaCalibParams_ar0330_parallel.o