
libapp-objs +=apps/flow/misc/misc_calibupdate.o
libapp-objs +=apps/flow/misc/misc_calibupdate_func.o
libapp-objs +=apps/flow/misc/misc_defsetting.o
libapp-objs +=apps/flow/misc/misc_defsetting_func.o
libapp-objs +=apps/flow/misc/misc_formatcard.o
libapp-objs +=apps/flow/misc/misc_formatcard_func.o
libapp-objs +=apps/flow/misc/misc_fwupdate.o
libapp-objs +=apps/flow/misc/misc_fwupdate_func.o
libapp-objs +=apps/flow/misc/misc_mvrecover.o
libapp-objs +=apps/flow/misc/misc_mvrecover_func.o
