ifneq ($(wildcard $(srctree)/$(src)/AmbaShell),)
obj-$(CONFIG_COMSVC_AMBASHELL) += AmbaShell/
endif

ifneq ($(wildcard $(srctree)/$(src)/AmbaSys),)
obj-$(CONFIG_COMSVC_AMBASYS) += AmbaSys/
endif

ifneq ($(wildcard $(srctree)/$(src)/AmbaTest),)
obj-$(CONFIG_COMSVC_AMBATEST) += AmbaTest/
endif

ifneq ($(wildcard $(srctree)/$(src)/FwUpdate),)
obj-$(CONFIG_COMSVC_FWUPDATE) += FwUpdate/
endif

ifneq ($(wildcard $(srctree)/$(src)/misc),)
obj-$(CONFIG_COMSVC_MISC) += misc/
endif

ifneq ($(wildcard $(srctree)/$(src)/image),)
obj-$(CONFIG_COMSVC_IMAGE) += image/
endif

ifneq ($(wildcard $(srctree)/$(src)/tune),)
obj-$(CONFIG_COMSVC_TUNE) += tune/
endif

