
libapp-objs +=peripheral_mod/vin/sensor/imx179_a12/AmbaIQParamImx179_A12.o
libapp-objs +=peripheral_mod/vin/sensor/imx179_a12/sensor_imx179_a12.o
libapp-objs +=peripheral_mod/vin/sensor/imx179_a12/AmbaCalibParams_imx179.o
