ifneq ($(wildcard $(srctree)/$(src)/core),)
obj-y += core/
endif

ifneq ($(wildcard $(srctree)/$(src)/ml),)
obj-y += hal/
endif

ifneq ($(wildcard $(srctree)/$(src)/imgproc),)
obj-y += imgproc/
endif

ifneq ($(wildcard $(srctree)/$(src)/objdetect),)
obj-y += objdetect/
endif

ifneq ($(wildcard $(srctree)/$(src)/ml),)
obj-y += ml/
endif

