
ifneq ($(wildcard $(srctree)/$(src)/connected),)
obj-$(CONFIG_APP_CONNECTED) += connected/
endif

ifneq ($(wildcard $(srctree)/$(src)/policecam),)
obj-$(CONFIG_APP_POLICECAM) += policecam/
endif

ifneq ($(wildcard $(srctree)/$(src)/cardv),)
obj-$(CONFIG_APP_CARDV) += cardv/
endif

ifneq ($(wildcard $(srctree)/$(src)/connectedmultivin),)
obj-$(CONFIG_APP_CONNECTED_MULTI_VIN) += connectedmultivin/
endif